In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
%precision 3

'%.3f'

In [2]:
sample = np.arange(10)

In [5]:
sample

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
sample_slice = sample[0:5]
sample_slice

array([0, 1, 2, 3, 4])

In [7]:
sample_slice[0:3] = 10

In [12]:
sample_copy = np.copy(sample)
sample_copy[0:3] = 20

array([10, 10, 10,  3,  4,  5,  6,  7,  8,  9])

In [14]:
cond_data = np.array([True,True,False,False,True])
x_array = np.array([1,2,3,4,5])
y_array = np.array([100,200,300,400,500])
np.where(cond_data,x_array,y_array)

array([  1,   2, 300, 400,   5])

In [15]:
np.unique(cond_data)

array([False,  True])

In [16]:
cond_data

array([ True,  True, False, False,  True])

In [35]:
# 特異値分解
A = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])
U, s, Vs = sp.linalg.svd(A)
m, n = A.shape
S = sp.linalg.diagsvd(s,m,n)
print('USV=\n', U@S@V)

USV=
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [43]:
import math

def calc_π(x):
    return 4/(1 + x**2)

print(sp.integrate.quad(calc_π, 0, 1))
print(sp.integrate.quad(lambda x: 4/(1 + x**2), 0, 1))

(3.141592653589793, 3.487868498008632e-14)
(3.141592653589793, 3.487868498008632e-14)
